# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- 12_hana

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: CmdLine@2
  inputs:
    script: 'npm install -g mbt @sap/cds-dk'
  displayName: Install CAP Build Tools and CAP Runtime Env

- script: mbt build -p=cf -s=$(Agent.BuildDirectory)/s/app1
  displayName: MTA Build

- script: ls $(Agent.BuildDirectory)/s/app1/mta_archives
  displayName: validate

- script : |
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  displayName: Add the Cloud Foundry Foundation public key and package repository to your system by running

- script : sudo apt-get update
  displayName: Update your local package index by running

- script : sudo apt-get install cf8-cli
  displayName: Install CF

- script: cf install-plugin multiapps -f
  displayName: Install Cloud Runtime Dependency

- script: cf login -a $(api-url) -u $(dev-user) -p $(dev-password) -o $(dev-org) -s $(space)
  displayName: Login into CF Space

- script: cf deploy $(Agent.BuildDirectory)/s/app1/mta_archives/app1_1.0.0.mtar
  displayName: Deploy to CF Space
